# Generated by Django 4.1.7 on 2023-02-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BooksCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('no_of_pages', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LaptopCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('series', models.CharField(max_length=100)),
                ('screen_size', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('cpu_model', models.CharField(max_length=20)),
                ('ram', models.IntegerField()),
                ('operating_system', models.CharField(choices=[('Windows', 'Windows'), ('Linux', 'Linux'), ('Mac', 'Mac')], max_length=50)),
                ('graphics', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MobileCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('os', models.CharField(choices=[('Android', 'Android'), ('IOS', 'IOS'), ('Windows', 'Windows')], max_length=30)),
                ('cellular_tech', models.CharField(choices=[('2G', '2G'), ('3G', '3G'), ('4G', '4G'), ('5G', '5G')], max_length=2)),
            ],
        ),
    ]
